### ISSUE TITLE
Ignore self-signed SSL cert verification

### ISSUE THREAD

**Issue by ngan** [probot/smee#102]
We use https in development (using puma-dev) with a self-signed ssl cert. Smee client uses superagent which doesn't expose an option to ignore errors. In fact, the creator is pretty against it: https://github.com/visionmedia/superagent/issues/926.

Considering that smee is used for development, it would be nice to not have to suffer this simply because superagent is against it.

**Comment by kadler** [comment]
Have you looked at [mkcert](https://github.com/FiloSottile/mkcert)?

**Comment by quarckster** [comment]
Just specify `NODE_EXTRA_CA_CERTS` environment variable with a path to your certificate in pem format.

**Comment by ngan** [comment]
> Have you looked at [mkcert](https://github.com/FiloSottile/mkcert)?

Pretty cool. Thanks!

**Comment by Midacts** [comment]
Thanks. This worked for me.
`NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt`
