### ISSUE TITLE
Add date into smee client log

### ISSUE THREAD

**Issue by quarckster** [probot/smee#109]
Currently, smee client produces such lines in the log:
```
Forwarding https://smee.io/channel_id to some_url
Connected https://smee.io/channel_id
POST some_url - 200
```

It would be nice to have dates there:
```
Mar 18 12:57:14 Forwarding https://smee.io/channel_id to some_url
Mar 18 12:57:15 Connected https://smee.io/channel_id
Mar 18 12:57:16 POST some_url - 200
```

**Comment by JasonEtco** [comment]
@quarckster are you asking about the CLI? Right now, you can pass a logger to the `SmeeClient` class (copied from [Probot's built-in Smee support](https://github.com/probot/probot/blob/master/src/webhook-proxy.ts):

```js
const SmeeClient = require('smee-client')
const smee = new SmeeClient({
  logger: opts.logger,
  source: opts.url,
  target: `http://localhost:${opts.port}${opts.path}`
})
```

**Comment by JasonEtco** [comment]
I'm going to close this because of inactivity, and because I'm pretty sure that ☝️ will do the trick. Feel free to reopen if I'm mistaken!
