### ISSUE TITLE
Persist deliveries across page loads

### ISSUE THREAD

**Issue by zeke** [probot/smee#39]
I was bummed to see my events disappear when I refreshed the page in my browser. Can we store them in localStorage or something?

**Comment by JasonEtco** [comment]
Sure! Do you want to PR that?

**Comment by zeke** [comment]
To play devil's advocate: adding this feature will make it easier to put off writing tests, which we want to discourage.

I might not be able to get to this right away, but the next time I use smee I may take a shot at it.

**Comment by JasonEtco** [comment]
Ok no worries, I'll take it 👍 And I'm not worried about putting off writing tests, but we can always tweak some messaging to reflect the need for tests.
