### ISSUE TITLE
Validate URL, report correct error

### ISSUE THREAD

**Issue by JasonEtco** [probot/smee#43]
I had the following set in my `.env`:

```
WEBHOOK_PROXY_URL=https:/smee.io/CHANNEL
```

It took me a while to find the problem, but there's only one `/` in `https://`. This resulted in a stream of errors from Probot, spamming my terminal as it tried to reconnect:

```
03:13:42.044Z ERROR probot:  (type=error)
```

![image](https://user-images.githubusercontent.com/10660468/36518475-8b1b1eea-1754-11e8-9c57-ca7192e21c54.png)

This should be caught earlier by the `smee-client`.

Originally opened as https://github.com/probot/probot/issues/439

**Comment by knrt10** [comment]
@JasonEtco I am working on this issue but on running locally when I am trying to make changes in serve/components/Blank.js it is not reflecting in my localhost. I was verifying URL but not able to proceed due to this error. Please help?

**Comment by JasonEtco** [comment]
@knrt10 this logic should be implemented in the `client` package, not the `server`. Your work should be contained within the `client` directory of this repository, so you shouldn't need to change with the front-end React components.

**Comment by knrt10** [comment]
@JasonEtco thanks for info will do according that.

**Comment by knrt10** [comment]
@JasonEtco Is there any way that while running smee on localhost I can receive webhooks?

**Comment by JasonEtco** [comment]
@knrt10 you can use [localtunnel.me](https://localtunnel.me), but because this error should appear when the Smee starts (not when it receives webhooks), this shouldn't be necessary.

**Comment by knrt10** [comment]
Ok. Thanks for info. Let me try and implement that.

**Comment by knrt10** [comment]
@JasonEtco Please check my PR. Thanks in advance.

**Comment by knrt10** [comment]
@JasonEtco please close this.
