### ISSUE TITLE
Add "pinned" events

### ISSUE THREAD

**Issue by JasonEtco** [probot/smee#53]
I had an idea: imagine if you could "pin" an event so that it'd always stay at the top of the page. This can be useful for replaying the same event, and for hitting the `Clear deliveries` button (pinned events would not be removed).

Would this be useful? It wouldn't be too hard to implement, it would be entirely client-side (and would persist via local storage, probably just an array of event ids).

cc @probot/maintainers 🤖

**Comment by hiimbex** [comment]
Yes! I always said the in advanced deliveries on GitHub there should be sorting/pinning/searching options, so makes sense for smee
