### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by JasonEtco** [probot/smee#65]
What if Smee could persist data? Wouldn't it be great if channels could be reused while keeping the same payload history across devices and teams? I think so!

I'd like to explore using Redis as a short-term storage solution for Smee. This is how I'm thinking it should work:

* Payloads have a maximum lifespan of 1 week (open to thoughts on this, just gettin' the ball rolling with a number)
* Redis key/values will look like `channel:payload.id => JSON.stringify(payload)`
* On load for `smee.io/:channel`, lookup all keys starting with `channel`(which I think we would use [`SCAN`](https://redis.io/commands/scan) for, someone who actually knows Redis please chime in)
* We would remove the `localStorage` functionality, and instead maybe server-side render? Or provide a new route like `/:channel/deliveries` that is `fetch`'d on `componentDidMount()`

cc @gautam @johnkpaul, y'all were asking about this the other day
cc @tcbyrd @bkeepers

**Comment by gautamarora** [comment]
yes please, this would be so awesome!!

possibly related, how about a replay feature? I would love to be able to take a selection of events from smee, and put then in a timed order to fire so I can test my entire bot workflow.

**Comment by JasonEtco** [comment]
That's pretty interesting @gautamarora - I'm not sure that we have the bandwidth to figure out how that'd all work and then implement it. If you want to get started on a PR or an issue explaining the implementation we can definitely go from there.

cc @wilhelmklopp - if I remember, we were talking about grouping events into "scenarios" or something a while ago.
