### ISSUE TITLE
Smee online data doesn't refresh

### ISSUE THREAD

**Issue by wolfy1339** [probot/smee#85]
The webhooks received by smee, are not updating on the web UI, but they are being recieved by my probot app.

The data showed is over 1 month old.

**Comment by wolfy1339** [comment]
If i leave it open then re-send the webhook, it works fine

**Comment by JasonEtco** [comment]
That's expected; Smee doesn't store webhook payloads, your browser does via `localStorage`. We've talked about real, persistent storage but that's a burden we're not prepared to take on right now. Apologies if that isn't clear - if you'd like to open a PR adding a message about how this works into the UI I'd be open to it!
