### ISSUE TITLE
Separate smee-client and smee-server into separate repositories

### ISSUE THREAD

**Issue by JasonEtco** [probot/smee#87]
I'd like to chat about moving `smee-client` and the actual server into two separate repositories. My main motivation to do that is to ease contributions (contributing to the two is confusing, including for me) make build times faster (CI will have to test half the code).

What do y'all think? Is this something worth the small amount of effort, or is it _less_ confusing the way it is now?

cc @tcbyrd

**Comment by gr2m** [comment]
From my experience I’d say do it, there will probably be different contributors working on the client tja the server

**Comment by macklinu** [comment]
I agree with having separate repos, as it has been a little confusing at times making sure I `cd` into the right directory when installing, starting the dev server, and running tests. 👍

**Comment by tcbyrd** [comment]
@JasonEtco 👍 Also I think it means we can iterate on the server as a separate thing. We should setup probably setup some automation to ensure they're tested against each other, but I like the idea.

**Comment by JasonEtco** [comment]
> We should setup probably setup some automation to ensure they're tested against each other

Yeah, good call. Zero code is shared between the client and server, so it might be tricky to do - but interestingly we don't already have any tests that work integrate both; so we're not _losing_ anything in the move, though it may be more difficult.

Sounds like three 👍s! Thanks all for your quick response 😊 Now, how do we feel about these names for the two repos?

* `smee-client`
* `smee-server`

We can hold on to `smee` and archive it, with links to those two in the README. Thoughts?

**Comment by tcbyrd** [comment]
One issue is the npm package is called `smee-client`, which right now also includes the CLI and is what some people have said they're using in production. I think it could potentially be confusing if there's still `smee-client`, but it doesn't do the server part anymore. What if we did `smee-ui` and `smee-server`?

**Comment by JasonEtco** [comment]
ha - actually I meant that `smee-client` would continue to be the CLI tool, and `smee-server` would be https://smee.io. Thats what the directories are called right now - but its confusing.

**Comment by tcbyrd** [comment]
d'oh. You're right. Then can we just call the server repo `smee.io` to avoid confusion?

**Comment by JasonEtco** [comment]
Ooh that's a great idea. So:

* `smee.io`
* `smee-client`

OR:

* `smee.io`
* `smee`

Or is that too confusing? Either way we should clearly describe each one in its README.

**Comment by tcbyrd** [comment]
> smee.io
> smee-client

One is the web app, one is the CLI. Makes the most sense to me. I think it's safe to rename this repository to `smee-client` to match the npm package, then we get redirects from `probot/smee` to `probot/smee-client` automatically and if anyone wants to help contribute the web app we can call that out in the README that we've moved the `/server` bits to `probot/smee.io`.

**Comment by JasonEtco** [comment]
Great, I love that plan. Should have time to act on it at the end of the week.

**Comment by JasonEtco** [comment]
Making a note for myself - if we can bring over the Git history into `probot/smee.io` that'd be rad, there's a handy help doc for it: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by wolfy1339** [comment]
Not stale.
________________________________
