### ISSUE TITLE
Server should forward query strings

### ISSUE THREAD

**Issue by rpetti** [probot/smee#98]
Would it be possible to allow the server to forward query strings? Here's our use-case:

We are using smee to forward webhooks from our git system to a Jenkins server. Jenkins needs the repository URL passed in as a query string in order for it to be matched to jobs correctly:

```
http://jenkins.local:8081/git/notifyCommit?url=git@ourgitserver.com:group/repo.git
```

We would like to be able to specify this query string on the git server's webhook configuration as such:

```
https://smee.local/qyfFcBhyEfMl0k3o?url=git@ourgitserver.com:group/repo.git
```

But this doesn't currently work. The only way to forward these types of hooks is to set up a channel and client for _each_ repository, and hard code the query string into the client's -P (path) parameter.

**Comment by JasonEtco** [comment]
Closed by #100 - thanks @rpetti ✨
